server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json
    min-response-size: 512
  http2:
    enabled: true

spring:
  application:
    name: ntu-booking-movie

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking-movie}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: HikariPool
      connection-test-query: SELECT 1
      data-source-properties:
        cache-prep-stmts: true
        prep-stmt-cache-size: 256
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true

  elasticsearch:
    uris: http://localhost:9200
    username: elastic  # nếu có authentication
    password: password # nếu có authentication
    connection-timeout: 5s
    socket-timeout: 30s

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: true
    open-in-view: false

  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
    enabled: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/init/data.sql
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.zaxxer.hikari: DEBUG

payment:
  momo:
    environment: dev
    return-url: http://localhost:8080/momo/momo-callback #callback user
    notify-url: http://localhost:8080/momo/momo-callback/backend  #callback backend
