-- Movie sample data
-- INSERT INTO TBL_MOVIE
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", AGE_RATING, DESCRIPTION, GENRE, POSTER_URL, RELEASE_DATE, RUNNING_TIME, TITLE, TRAILER_URL)
-- VALUES(1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, 0, 'Buộc phải cân bằng giữa vai trò anh hùng với sức mạnh của mối quan hệ gia đình, Fantastic Four phải bảo vệ Trái Đất khỏi vị thần không gian hung dữ tên là Galactus và sứ giả bí ẩn của hắn, Silver Surfer.', 'Hài hước,Hành động', 'https://files.betacorp.vn/media%2fimages%2f2025%2f07%2f16%2fbeta%2D400x633%2D160023%2D160725%2D63.png', '2025-08-01', 200, 'Bộ Tứ Siêu Đẳng: Bước Đi Đầu Tiên 1', 'https://www.youtube.com/embed/KHfU57tzFjk');

-- INSERT INTO TBL_MOVIE
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", AGE_RATING, DESCRIPTION, GENRE, POSTER_URL, RELEASE_DATE, RUNNING_TIME, TITLE, TRAILER_URL)
-- VALUES(2, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, 1, '111', '[Hài hước]', 'https://files.betacorp.vn/media%2fimages%2f2025%2f07%2f16%2fbeta%2D400x633%2D160023%2D160725%2D63.png', '2025-08-14', 1, 'a', 'https://www.youtube.com/embed/KHfU57tzFjk');

-- INSERT INTO TBL_MOVIE
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", AGE_RATING, DESCRIPTION, GENRE, POSTER_URL, RELEASE_DATE, RUNNING_TIME, TITLE, TRAILER_URL)
-- VALUES(3, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, 3, '1111', '[Hành động]', 'https://files.betacorp.vn/media%2fimages%2f2025%2f07%2f16%2fbeta%2D400x633%2D160023%2D160725%2D63.png', '2025-08-29', 1, 'qqq', 'https://www.youtube.com/embed/nVOgLUHhfGA');

-- Theater sample data
-- INSERT INTO TBL_THEATER
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", ADDRESS, "NAME", PHONE, WARD_ID, IS_DEFAULT, HOTLINE)
-- VALUES(1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, NULL, NULL, NULL, NULL, TRUE, NULL);

-- Room sample data
-- INSERT INTO TBL_ROOM
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", CAPACITY, "NAME", ROOM_TYPE_ID, THEATER_ID, IS_DEFAULT)
-- VALUES(1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, 30, ' NTU Hoài Đức', NULL, 1, NULL);

-- Showtime sample data
-- INSERT INTO TBL_SHOWTIME
-- (ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, "VERSION", END_TIME, START_TIME, MOVIE_ID, ROOM_ID)
-- VALUES(1, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL, 0, DATEADD('HOUR', 3, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP, 1, 1);
